#!/bin/sh
# Runs the specs inside an OpenResty container. test/run.sh starts the
# container and calls this script; CI runs this script directly in an
# OpenResty job container. Expects the repository at $WORK (default /work)
# and the fixtures already generated by test/run.sh or test/fixtures.sh.
set -eu
WORK="${WORK:-/work}"
# test/nginx.conf, the stubs and the fixture paths are fixed at /work, so a
# checkout elsewhere is linked there.
if [ "$WORK" != /work ]; then
	rm -rf /work && ln -s "$WORK" /work
fi
cd /work
luarocks install lua-resty-jwt >/dev/null 2>&1
luarocks install lua-resty-openssl >/dev/null 2>&1
luarocks install lua-resty-http >/dev/null 2>&1
echo "== token_spec"
resty -I "$WORK/src" -I "$WORK/test" test/token_spec.lua
echo "== jwks fixture"
resty -I "$WORK/src" -I "$WORK/test" -e '
	local cjson = require "cjson"
	local key = assert(require("portier.token").key_load())
	local f = assert(io.open("/work/test/fixtures/jwks.json", "w"))
	f:write(cjson.encode({ keys = { key.jwk } }))
	f:close()
	print("kid " .. key.kid)
'
echo "== nginx"
mkdir -p /tmp/nginx-body /var/cache/nginx/portier /etc/portier/webroot
cp "$WORK/webroot/index.html" /etc/portier/webroot/
/usr/local/openresty/nginx/sbin/nginx -c "$WORK/test/nginx.conf"
echo "== sp_spec"
sh test/sp_spec.sh; rc1=$?
echo "== idp_spec"
sh test/idp_spec.sh; rc2=$?
/usr/local/openresty/nginx/sbin/nginx -c "$WORK/test/nginx.conf" -s quit
[ $rc1 -eq 0 ] && [ $rc2 -eq 0 ]
